name: Run danger

on: [pull_request]

jobs:
  build:

    # Note:
    # Maybe can use linux image
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      # with:
      #   ref: ${{ github.head_ref }}

    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - name: Cache bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundler-${{ hashFiles('Gemfile.lock') }}

    - name: Setup
      run: bundle

    - name: Dump GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${GITHUB_CONTEXT}"

    - name: Run rubocop --auto-correct
      run: |
        M=`git config -l`
        echo "--- git config --"
        echo "$M"
        echo "--- git remote --"
        M=`git remote -v`
        echo "$M"
        git config --global user.name 'Yusuke Hosonuma'
        git config --global user.email 'tobi462@users.noreply.github.com'
        git checkout -b ${{ github.head_ref }} origin/${{ github.head_ref }}
        if [ ! "bundle exec rubocop --auto-correct" ]; then
          exit 0
        fi
        echo "--- git branch --"
        M=`git branch -a`
        echo "$M"
        echo 'foo' >> README.md
        git add -u
        git diff-index --quiet HEAD -- || git commit -m '[ci skip] $ rubocop --auto-correct'
        git push
        echo 'Good!!'
        exit 0

    - name: Run danger
      run: bundle exec danger

    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
