name: Run danger

on: [pull_request]

jobs:
  build:

    # Note:
    # Maybe can use linux image
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Ref:
    # https://github.com/actions/checkout#fetch-all-branches
    - name: Fetch all branches
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - name: Cache bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundler-${{ hashFiles('Gemfile.lock') }}

    - name: Setup
      run: |
        bundle

    - name: Run rubocop --auto-correct and push
      shell: bash -ex {0}
      run: |
        git config --global user.name 'Yusuke Hosonuma'
        git config --global user.email '2990285+YusukeHosonuma@users.noreply.github.com'
        git checkout -b ${{ github.head_ref }} origin/${{ github.head_ref }}
        bundle exec rubocop --auto-correct && true
        git add -u
        git commit -m '[ci skip] $ rubocop --auto-correct'
        git push

    - name: Run danger
      run: bundle exec danger

    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
